const now = Date.now()
const iso = (secondsAgo) => new Date(now - secondsAgo * 1000).toISOString()

export const demoAgents = [
  {
    id: 'AG-CLAUDE',
    name: 'Claude',
    tier: 'manager',
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    role: 'Manager produit / stratégie',
    status: 'active',
    cost_index: 1.7,
    quality_index: 0.95,
  },
  {
    id: 'AG-HERMES',
    name: 'Hermes',
    tier: 'ceo',
    provider: 'nous',
    model: 'hy3',
    role: 'CEO / Orchestration',
    status: 'active',
    cost_index: 0.4,
    quality_index: 0.9,
  },
  {
    id: 'AG-ANTIGRAVITY',
    name: 'Antigravity',
    tier: 'manager',
    provider: 'google',
    model: 'antigravity-code-agent',
    role: 'Orchestration code',
    status: 'active',
    cost_index: 1.3,
    quality_index: 0.92,
  },
  {
    id: 'AG-KIMI',
    name: 'Kimi',
    tier: 'manager',
    provider: 'moonshot',
    model: 'kimi-k3',
    role: 'Recherche / Données',
    status: 'paused',
    cost_index: 0.8,
    quality_index: 0.88,
  },
]

export const demoEvents = [
  { ts: iso(3600), type: 'mission.start', hash: 'demo-00', data: { mission: 'Knowledge Base Sync', domain: 'data', rules: 3 } },
  { ts: iso(3540), type: 'agent.assigned', hash: 'demo-00a', data: { agent: 'AG-KIMI', name: 'Kimi', model: 'kimi-k3', rule: 'knowledge-sync', cost: 0.28 } },
  { ts: iso(3510), type: 'agent.result', hash: 'demo-00b', data: { agent: 'AG-KIMI', name: 'Kimi', rule: 'knowledge-sync', violation: false, findings: 0, duration_ms: 30000 } },
  { ts: iso(3490), type: 'budget.eval', hash: 'demo-00c', data: { cost: 0.28, explorations: 1, reworks: 0, limits: { maxCost: 0.8 }, over: [] } },
  { ts: iso(3480), type: 'mission.closure', hash: 'demo-00d', data: { closure: 'LIVRAISON_AUTONOME', escalations: 0, rationale: 'Synchronisation terminée, contrôles conformes et aucun risque résiduel détecté.' } },
  { ts: iso(120), type: 'mission.start', hash: 'demo-01', data: { mission: 'Cortex Lab UI Audit', domain: 'frontend', target: 'web/src', rules: 6 } },
  { ts: iso(108), type: 'agent.assigned', hash: 'demo-02', data: { agent: 'AG-CLAUDE', name: 'Claude', model: 'claude-opus-4-8', rule: 'analysis-step', rationale: 'Meilleure aptitude produit et hiérarchie visuelle.', cost: 0.84 } },
  { ts: iso(92), type: 'check.run', hash: 'demo-03', data: { rule: 'UI-HIERARCHY', violation: false, findings: 0 } },
  { ts: iso(76), type: 'agent.result', hash: 'demo-04', data: { agent: 'AG-CLAUDE', name: 'Claude', rule: 'analysis-step', violation: false, findings: 3, duration_ms: 18000 } },
  { ts: iso(45), type: 'mission.start', hash: 'demo-05', data: { mission: 'Agent Gateway Audit', domain: 'backend', target: 'gateway', rules: 5 } },
  { ts: iso(42), type: 'agent.assigned', hash: 'demo-06', data: { agent: 'AG-HERMES', name: 'Hermes', model: 'hy3', rule: 'approval-required', rationale: 'Décision de sécurité et conformité gateway.', cost: 1.12 } },
  { ts: iso(32), type: 'mission.start', hash: 'demo-07', data: { mission: 'Data Pipeline Migration', domain: 'data', target: 'pipeline', rules: 5 } },
  { ts: iso(26), type: 'agent.assigned', hash: 'demo-08', data: { agent: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent', rule: 'task-started', rationale: 'Migration technique multi-fichiers.', cost: 0.56 } },
  { ts: iso(18), type: 'agent.result', hash: 'demo-09', data: { agent: 'AG-KIMI', name: 'Kimi', rule: 'source-found', violation: false, findings: 1, duration_ms: 9000 } },
  { ts: iso(12), type: 'agent.assigned', hash: 'demo-10', data: { agent: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent', rule: 'task-started', rationale: 'Deuxième lot de migration.', cost: 0.56 } },
  { ts: iso(8), type: 'agent.result', hash: 'demo-11', data: { agent: 'AG-CLAUDE', name: 'Claude', rule: 'analysis-step-completed', violation: false, findings: 0, duration_ms: 22000 } },
]

export const demoMissions = [
  {
    id: 'm_018f2a1b',
    source: 'cortex-ledger',
    name: 'Cortex Lab UI Audit',
    domain: 'Audit complet de l’interface et architecture UI/UX',
    target: 'web/src',
    status: 'running',
    phase: 'executing',
    progress: 72,
    started_at: demoEvents[5].ts,
    duration_ms: null,
    manager: { id: 'AG-CLAUDE', name: 'Claude', model: 'claude-opus-4-8' },
    agents: [{ id: 'AG-CLAUDE', name: 'Claude', model: 'claude-opus-4-8', mandates: 1, cost: 0.84 }],
    budget: { cost: 0.84, explorations: 2, reworks: 0, percentage: 42, limits: { maxCost: 2 } },
    checks: { total: 3, passed: 3, violations: 0, findings: 0, items: [demoEvents[7].data] },
    event_count: 5,
    latest_event: demoEvents[15],
    timeline: [demoEvents[5], demoEvents[6], demoEvents[7], demoEvents[8], demoEvents[15]],
  },
  {
    id: 'm_7c3d9e4f',
    source: 'cortex-ledger',
    name: 'Agent Gateway Audit',
    domain: 'Audit sécurité et conformité du système de gateway',
    target: 'gateway',
    status: 'escalated',
    phase: 'checking',
    progress: 40,
    started_at: demoEvents[9].ts,
    duration_ms: null,
    manager: { id: 'AG-HERMES', name: 'Hermes', model: 'hy3' },
    agents: [{ id: 'AG-HERMES', name: 'Hermes', model: 'hy3', mandates: 1, cost: 1.12 }],
    budget: { cost: 1.12, explorations: 1, reworks: 0, percentage: 45, limits: { maxCost: 2.5 } },
    checks: { total: 3, passed: 2, violations: 1, findings: 0, items: [] },
    escalations: 1,
    event_count: 2,
    latest_event: demoEvents[10],
    timeline: [demoEvents[9], demoEvents[10]],
  },
  {
    id: 'm_b12e3f7c',
    source: 'cortex-ledger',
    name: 'Data Pipeline Migration',
    domain: 'Migration et validation du pipeline de données',
    target: 'pipeline',
    status: 'running',
    phase: 'executing',
    progress: 38,
    started_at: demoEvents[11].ts,
    duration_ms: null,
    manager: { id: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent' },
    agents: [{ id: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent', mandates: 2, cost: 1.12 }],
    budget: { cost: 1.12, explorations: 2, reworks: 0, percentage: 93, limits: { maxCost: 1.2 } },
    checks: { total: 1, passed: 1, violations: 0, findings: 0, items: [] },
    event_count: 3,
    latest_event: demoEvents[14],
    timeline: [demoEvents[11], demoEvents[12], demoEvents[14]],
  },
  {
    id: 'm_91a8b2d1',
    source: 'cortex-ledger',
    name: 'Knowledge Base Sync',
    domain: 'Synchronisation de la base de connaissances',
    target: 'knowledge-base',
    status: 'autonomous',
    phase: 'closed',
    progress: 100,
    started_at: demoEvents[0].ts,
    finished_at: demoEvents[4].ts,
    duration_ms: 120000,
    closure: 'LIVRAISON_AUTONOME',
    closure_data: demoEvents[4].data,
    manager: { id: 'AG-KIMI', name: 'Kimi', model: 'kimi-k3' },
    agents: [{ id: 'AG-KIMI', name: 'Kimi', model: 'kimi-k3', mandates: 1, cost: 0.28 }],
    budget: { cost: 0.28, explorations: 1, reworks: 0, percentage: 35, limits: { maxCost: 0.8 } },
    checks: { total: 3, passed: 3, violations: 0, findings: 0, items: [] },
    escalations: 0,
    event_count: 5,
    latest_event: demoEvents[4],
    timeline: demoEvents.slice(0, 5),
  },
]

export const demoSummary = {
  total: 4,
  running: 2,
  needs_attention: 1,
  autonomous: 1,
  information: 0,
  escalated: 1,
  checks_failed: 1,
  budget_cost: 3.36,
  budget_limit: 6.5,
  latest_activity: iso(8),
}
