const now = Date.now()
const iso = (secondsAgo) => new Date(now - secondsAgo * 1000).toISOString()

export const demoAgents = [
  {
    id: 'AG-CLAUDE',
    name: 'Claude',
    tier: 'manager',
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    role: 'Manager produit / stratégie',
    status: 'active',
    cost_index: 1.7,
    quality_index: 0.95,
  },
  {
    id: 'AG-HERMES',
    name: 'Hermes',
    tier: 'ceo',
    provider: 'nous',
    model: 'hy3',
    role: 'CEO / Orchestration',
    status: 'active',
    cost_index: 0.4,
    quality_index: 0.9,
  },
  {
    id: 'AG-ANTIGRAVITY',
    name: 'Antigravity',
    tier: 'manager',
    provider: 'google',
    model: 'antigravity-code-agent',
    role: 'Orchestration code',
    status: 'active',
    cost_index: 1.3,
    quality_index: 0.92,
  },
  {
    id: 'AG-KIMI',
    name: 'Kimi',
    tier: 'manager',
    provider: 'moonshot',
    model: 'kimi-k3',
    role: 'Recherche / Données',
    status: 'paused',
    cost_index: 0.8,
    quality_index: 0.88,
  },
]

export const demoEvents = [
  { ts: iso(120), type: 'mission.start', hash: 'demo-01', data: { mission: 'Cortex Lab UI Audit', domain: 'frontend', rules: 6 } },
  { ts: iso(108), type: 'agent.assigned', hash: 'demo-02', data: { agent: 'AG-CLAUDE', name: 'Claude', model: 'claude-opus-4-8', rule: 'analysis-step', cost: 0.84 } },
  { ts: iso(92), type: 'check.run', hash: 'demo-03', data: { rule: 'UI-HIERARCHY', violation: false, findings: 0 } },
  { ts: iso(76), type: 'agent.result', hash: 'demo-04', data: { agent: 'AG-CLAUDE', name: 'Claude', rule: 'analysis-step', violation: false, findings: 3, duration_ms: 18000 } },
  { ts: iso(45), type: 'mission.start', hash: 'demo-05', data: { mission: 'Agent Gateway Audit', domain: 'backend', rules: 5 } },
  { ts: iso(42), type: 'agent.assigned', hash: 'demo-06', data: { agent: 'AG-HERMES', name: 'Hermes', model: 'hy3', rule: 'approval-required', cost: 1.12 } },
  { ts: iso(32), type: 'mission.start', hash: 'demo-07', data: { mission: 'Data Pipeline Migration', domain: 'data', rules: 5 } },
  { ts: iso(26), type: 'agent.assigned', hash: 'demo-08', data: { agent: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent', rule: 'task-started', cost: 0.56 } },
  { ts: iso(18), type: 'agent.result', hash: 'demo-09', data: { agent: 'AG-KIMI', name: 'Kimi', rule: 'source-found', violation: false, findings: 1, duration_ms: 9000 } },
  { ts: iso(12), type: 'agent.assigned', hash: 'demo-10', data: { agent: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent', rule: 'task-started', cost: 0.56 } },
  { ts: iso(8), type: 'agent.result', hash: 'demo-11', data: { agent: 'AG-CLAUDE', name: 'Claude', rule: 'analysis-step-completed', violation: false, findings: 0, duration_ms: 22000 } },
]

export const demoMissions = [
  {
    id: 'm_018f2a1b',
    name: 'Cortex Lab UI Audit',
    domain: 'Audit complet de l’interface et architecture UI/UX',
    status: 'running',
    phase: 'executing',
    progress: 72,
    started_at: iso(138),
    duration_ms: null,
    manager: { id: 'AG-CLAUDE', name: 'Claude', model: 'claude-opus-4-8' },
    agents: [{ id: 'AG-CLAUDE', name: 'Claude', model: 'claude-opus-4-8', cost: 0.84 }],
    budget: { cost: 0.84, percentage: 42, limits: { maxCost: 2 } },
    checks: { passed: 3, violations: 0, findings: 0 },
    latest_event: { type: 'analysis_step_completed', ts: iso(8), data: {} },
  },
  {
    id: 'm_7c3d9e4f',
    name: 'Agent Gateway Audit',
    domain: 'Audit sécurité et conformité du système de gateway',
    status: 'escalated',
    phase: 'checking',
    progress: 40,
    started_at: iso(342),
    duration_ms: null,
    manager: { id: 'AG-HERMES', name: 'Hermes', model: 'hy3' },
    agents: [{ id: 'AG-HERMES', name: 'Hermes', model: 'hy3', cost: 1.12 }],
    budget: { cost: 1.12, percentage: 45, limits: { maxCost: 2.5 } },
    checks: { passed: 2, violations: 1, findings: 0 },
    latest_event: { type: 'approval_required', ts: iso(120), data: {} },
  },
  {
    id: 'm_b12e3f7c',
    name: 'Data Pipeline Migration',
    domain: 'Migration et validation du pipeline de données',
    status: 'running',
    phase: 'executing',
    progress: 38,
    started_at: iso(83),
    duration_ms: null,
    manager: { id: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent' },
    agents: [{ id: 'AG-ANTIGRAVITY', name: 'Antigravity', model: 'antigravity-code-agent', cost: 0.56 }],
    budget: { cost: 0.56, percentage: 47, limits: { maxCost: 1.2 } },
    checks: { passed: 1, violations: 0, findings: 0 },
    latest_event: { type: 'task_started', ts: iso(12), data: {} },
  },
  {
    id: 'm_91a8b2d1',
    name: 'Knowledge Base Sync',
    domain: 'Synchronisation de la base de connaissances',
    status: 'closed',
    phase: 'closed',
    progress: 0,
    started_at: iso(3600),
    duration_ms: 0,
    manager: { id: 'AG-KIMI', name: 'Kimi', model: 'kimi-k3' },
    agents: [],
    budget: { cost: 0, percentage: 0, limits: { maxCost: 0.8 } },
    checks: { passed: 0, violations: 0, findings: 0 },
    latest_event: { type: 'idle', ts: iso(60), data: {} },
  },
]

export const demoSummary = {
  total: 5,
  running: 3,
  needs_attention: 1,
  autonomous: 5,
  information: 0,
  escalated: 1,
  checks_failed: 1,
  budget_cost: 4.82,
  budget_limit: 11.5,
  latest_activity: iso(8),
}
